#!/bin/bash

# Check if a class name is provided
if [ -z "$1" ]; then
  echo "Usage: ./run.sh <fully.qualified.ClassName>"
  echo "Example: ./run.sh com.rishi.dsa.trees.binary_tree_maximum_path_sum.Main"
  exit 1
fi

CLASS_NAME=$1

# Compile using Maven (only compile, don't run tests to save time)
echo "Compiling..."
mvn compile -q

if [ $? -ne 0 ]; then
  echo "Compilation failed."
  exit 1
fi

# Run the class using the classpath generated by Maven
echo "Running $CLASS_NAME..."
mvn exec:java -Dexec.mainClass="$CLASS_NAME" -q


# ./run.sh com.rishi.dsa.trees.binary_tree_maximum_path_sum.Main